import { test } from 'node:test';
import assert from 'node:assert/strict';
import { outcome, move, story, type Game, type Mark } from '../src/lib/game';
const game = (override: Partial<Game> = {}): Game => ({id:'g',player_x_id:'a',player_o_id:'b',player_x_name:'Alice',player_o_name:'Bob',status:'playing',board:Array(9).fill(''),current_turn:'X',winner_id:null,winning_cells:[],created_at:'',updated_at:'',finished_at:null,finish_reason:null,...override});
test('all horizontal, vertical and diagonal wins',()=>{for(const cells of [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]]){for(const mark of ['X','O'] as const){const board:Mark[]=Array(9).fill('');cells.forEach(i=>board[i]=mark);assert.deepEqual(outcome(board),{winner:mark,cells,draw:false});}}});
test('draw and unfinished board',()=>{assert.equal(outcome(['X','O','X','X','O','O','O','X','X']).draw,true);assert.equal(outcome(Array(9).fill('')).draw,false);});
test('invalid cell, occupied cell, wrong turn, outsider and finished game',()=>{for(const cell of [-1,9,1.5,NaN])assert.throws(()=>move(game(),'a',cell),/valid square/);assert.throws(()=>move(game({board:['X','','','','','','','','']}),'a',0),/occupied/);assert.throws(()=>move(game(),'b',0),/turn/);assert.throws(()=>move(game(),'outsider',0),/not a player/);assert.throws(()=>move(game({status:'finished'}),'a',0),/not accepting/);});
test('move is immutable, alternates turns, rejects consecutive moves',()=>{const original=game();const next=move(original,'a',0);assert.equal(original.board[0],'');assert.equal(next.board[0],'X');assert.equal(next.current_turn,'O');assert.throws(()=>move(next,'a',1),/turn/);});
test('winning move saves result, cells and story; draw saves completion',()=>{const g=move(game({board:['X','X','','O','O','','','','']}),'a',2);assert.equal(g.status,'finished');assert.equal(g.winner_id,'a');assert.deepEqual(g.winning_cells,[0,1,2]);assert.ok(g.finished_at);assert.match(story(g),/Alice won; Bob lost/);const draw=move(game({board:['X','O','X','X','O','O','O','X','']}),'a',8);assert.equal(draw.finish_reason,'draw');assert.equal(draw.winner_id,null);});
