import { test } from 'node:test';
import assert from 'node:assert/strict';
import { LocalStore } from '../src/lib/local-store';
function setup(){const db=new LocalStore(':memory:');return {db,a:db.register('alice@example.com','password123','Alice'),b:db.register('bob@example.com','password123','Bob'),c:db.register('charlie@example.com','password123','Charlie')};}
test('accounts, password verification, session expiry and logout',()=>{const {db,a}=setup();assert.deepEqual(db.user(a.token),a.user);assert.equal(db.login('ALICE@example.com','password123').user.id,a.user.id);assert.throws(()=>db.login('alice@example.com','wrong'),/incorrect/);assert.throws(()=>db.register('alice@example.com','password123','Alice'),/Unable/);db.logout(a.token);assert.equal(db.user(a.token),undefined);db.db.close();});
test('challenge lifecycle, one active game, cancellation and private history',()=>{const {db,a,b,c}=setup();const g=db.create(a.user);assert.equal(db.snapshot(a.user).challenges.length,0);assert.equal(db.snapshot(b.user).challenges[0].id,g.id);assert.throws(()=>db.create(a.user),/current match/);assert.throws(()=>db.join(a.user,g.id));assert.throws(()=>db.cancel(b.user,g.id),/creator/);db.cancel(a.user,g.id);assert.equal(db.snapshot(b.user).challenges.length,0);assert.throws(()=>db.join(b.user,g.id),/cancelled/);const next=db.create(a.user);db.join(b.user,next.id);assert.throws(()=>db.join(c.user,next.id),/already joined/);assert.throws(()=>db.cancel(a.user,next.id));assert.throws(()=>db.play(c.user,next.id,0),/not a player/);assert.equal(db.snapshot(c.user).active,null);assert.equal(db.snapshot(c.user).history.length,0);db.db.close();});
test('two players finish a match; refresh restores board and both histories',()=>{const {db,a,b,c}=setup();const g=db.create(a.user);db.join(b.user,g.id);for(const [player,cell] of [[b,0],[a,3],[b,1],[a,4],[b,2]] as const)db.play(player.user,g.id,cell);const first=db.snapshot(a.user),second=db.snapshot(b.user);assert.equal(first.active,null);assert.equal(first.stats.losses,1);assert.equal(second.stats.wins,1);assert.equal(first.history[0].board[2],'O');assert.deepEqual(first.history,second.history);assert.equal(db.snapshot(c.user).history.length,0);assert.throws(()=>db.play(b.user,g.id,5),/not accepting/);assert.ok(db.create(a.user));db.db.close();});
test('resignation awards opponent a win and is immutable',()=>{const {db,a,b,c}=setup();const g=db.create(a.user);db.join(b.user,g.id);assert.throws(()=>db.resign(c.user,g.id));db.resign(a.user,g.id);assert.equal(db.game(g.id).winner_id,b.user.id);assert.equal(db.game(g.id).finish_reason,'resignation');assert.throws(()=>db.resign(b.user,g.id));db.db.close();});
test('failed operations roll back without changing state',()=>{const {db,a,b}=setup();const g=db.create(a.user);db.join(b.user,g.id);assert.throws(()=>db.play(a.user,g.id,0),/turn/);assert.equal(db.game(g.id).board.filter(Boolean).length,0);db.play(b.user,g.id,0);assert.equal(db.snapshot(a.user).active?.board[0],'O');db.db.close();});
