'use client';
import { useState } from 'react';
import { ArrowUpRight, ArrowLeft, Check, ChevronRight, CircleDot, Flag, Grid2X2, History as HistoryIcon, LoaderCircle, LogOut, Radio, RefreshCw, Swords, WifiOff, X } from 'lucide-react';
import { isSupabase } from '@/lib/backend';
import { resultText, story } from '@/lib/game';
import { useGameRoom } from '@/hooks/use-game-room';
import { AuthForm } from './auth-form';
import { Board } from './board';
import { History } from './history';
export default function TickTack(){
  const room=useGameRoom();const {user,data,game,busy}=room;
  const [tab,setTab]=useState<'lobby'|'history'>('lobby');const [resigning,setResigning]=useState(false);
  const yourMark=game?.player_x_id===user?.id?'X':'O';
  const yourTurn=game?.status==='playing'&&game.current_turn===yourMark;
  const opponentId=game?.player_x_id===user?.id?game?.player_o_id:game?.player_x_id;
  const opponentOnline=!!opponentId&&!!data?.onlineIds.includes(opponentId);
  return <div className="app-shell"><header><a className="brand" href="/" aria-label="QALIM tickTack home"><span className="brand-icon"><span>×</span><span>○</span></span><span className="brand-name"><small>QALIM</small>tickTack<span className="brand-dot">.</span></span></a><div className="header-right"><span className="edition">{isSupabase?'ONLINE PLAY':'LOCALHOST EDITION'}</span>{user&&<><span className="user-chip"><span className="avatar">{user.username.slice(0,1).toUpperCase()}</span><span>{user.username}</span></span><button className="icon-button" disabled={busy} onClick={()=>void room.logout()} aria-label="Sign out" title="Sign out"><LogOut size={18}/></button></>}</div></header>
  <main>{!room.ready?<div className="initial-loading"><LoaderCircle className="spin"/><p>Getting your board ready…</p></div>:!user?<div className="welcome-layout"><section className="welcome"><div className="eyebrow"><span className="tiny-dot"/> TWO PLAYERS. NINE SQUARES.</div><h1>A little board.<br/>A big <em>rivalry.</em></h1><p>The classic you know, with a real opponent.<br/>Find a challenge. Take your turn. Make your mark.</p><div className="welcome-board" aria-hidden="true"><span className="hero-x">×</span><span/><span className="hero-o">○</span><span/><span className="hero-x">×</span><span/><span className="hero-o">○</span><span/><span className="hero-x highlight">×</span></div><div className="welcome-foot"><Check size={17}/> Real-time matches <span/> Saved match history <span/> Made for two</div></section><AuthForm onUser={room.setUser} notice={room.error}/></div>:<>
  <div className="topline"><span className="breadcrumb">PLAYROOM <ChevronRight size={13}/>{game?'YOUR MATCH':tab==='history'?'MATCH HISTORY':'LOBBY'}</span><span className={`connection ${room.connected?'':'disconnected'}`}>{room.connected?<Radio size={13}/>:<WifiOff size={13}/>} {room.connected?'Live updates connected':'Reconnecting · retrying automatically'}</span></div>
  {room.error&&<div className="error-banner" role="alert"><span>{room.error}</span><button className="icon-button" aria-label="Dismiss error" onClick={()=>room.setError('')}><X size={16}/></button></div>}
  {!data?<div className="initial-loading"><LoaderCircle className="spin"/><p>Opening your playroom…</p><button className="text-button" onClick={()=>void room.refresh()}>Try again</button></div>:game?<div className="game-layout"><section className="game-main"><div className="eyebrow">{game.status==='waiting'?'YOUR CHALLENGE IS OPEN':game.status==='finished'?'THAT’S A MATCH':'MAKE YOUR MARK'}</div><h1>{game.status==='waiting'?'A worthy rival awaits.':game.status==='finished'?resultText(game,user.id):yourTurn?'Your move.':'Their move.'}</h1><p className="muted">{game.status==='waiting'?'Your challenge is in the lobby. The game starts when someone joins.':game.status==='finished'?story(game):'Three in a row. One winner. Make every square count.'}</p><div className="player-strip"><div className={game.current_turn==='X'&&game.status==='playing'?'active-player':''}><span className="player-symbol x">×</span><div><strong>{game.player_x_name}{game.player_x_id===user.id?' (you)':''}</strong><small>Player X</small></div></div><span className="vs">VS</span><div className={game.current_turn==='O'&&game.status==='playing'?'active-player':''}><span className="player-symbol o">○</span><div><strong>{game.player_o_name?`${game.player_o_name}${game.player_o_id===user.id?' (you)':''}`:'Waiting…'}</strong><small>Player O</small></div></div></div><Board game={game} onMove={game.status==='playing'?cell=>void room.perform('move',game.id,cell):undefined} disabled={!yourTurn||busy}/><div className="board-status" aria-live="polite">{busy?<><LoaderCircle size={16} className="spin"/> Saving…</>:game.status==='waiting'?<><span className="pulse-dot"/> Waiting for an opponent</>:game.status==='finished'?<><Check size={16}/>{game.winner_id?'Match complete':'A well-played draw'}</>:<><CircleDot size={16}/>{yourTurn?'You’re playing '+yourMark+' — choose a square':`${game.current_turn==='X'?game.player_x_name:game.player_o_name} is playing ${game.current_turn}`}</>}</div>
  {game.status==='playing'&&!opponentOnline&&<p className="offline-note"><WifiOff size={14}/> Opponent appears offline. Your match is saved; they can reconnect.</p>}
  <div className="game-actions">{game.status==='waiting'?<button className="secondary" disabled={busy} onClick={()=>void room.perform('cancel',game.id)}>Cancel challenge</button>:game.status==='finished'?<button className="primary" onClick={()=>{room.back();setTab('lobby');}}>Back to lobby <ArrowUpRight size={18}/></button>:resigning?<><span>Resign and award the win to your opponent?</span><button className="danger" disabled={busy} onClick={()=>{void room.perform('resign',game.id);setResigning(false);}}>Resign</button><button className="secondary" onClick={()=>setResigning(false)}>Keep playing</button></>:<button className="text-button" disabled={busy} onClick={()=>setResigning(true)}><Flag size={15}/> Resign match</button>}</div></section><aside className="match-side"><span className="side-symbols">× ○</span><h3>{game.status==='finished'?'A match to remember.':'Simple rules. Good game.'}</h3><p>{game.status==='finished'?'Your final board and result are saved in match history. Ready for another round?':'X goes first. Take turns placing your mark. Connect three across, down, or diagonally to win.'}</p><div className="side-line"/><span className="eyebrow">MATCH DETAILS</span><dl><div><dt>Started</dt><dd>{new Date(game.created_at).toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'})}</dd></div><div><dt>Moves played</dt><dd>{game.board.filter(Boolean).length} / 9</dd></div><div><dt>Your mark</dt><dd>{yourMark}</dd></div><div><dt>Opponent</dt><dd>{game.status==='waiting'?'Not joined':opponentOnline?'Connected':'Away'}</dd></div></dl></aside></div>:<>
  <section className="lobby-intro"><div><div className="eyebrow">A FAMILIAR GAME. A FRESH CHALLENGE.</div><h1>Your next move starts here<span>.</span></h1><p>Pull up a seat, {user.username}. There’s always room for a good rivalry.</p></div><div className="intro-symbols" aria-hidden="true"><span>×</span><span>○</span></div></section>
  <div className="dashboard"><aside className="dashboard-aside"><div className="challenge-card"><Swords size={24}/><h2>Set the challenge.</h2><p>Open a board and let your next opponent come to you.</p><button className="primary wide" disabled={busy} onClick={()=>{setTab('lobby');void room.perform('create');}}>{busy?<LoaderCircle className="spin" size={18}/>:<>Create challenge <ArrowUpRight size={19}/></>}</button><small>You’ll play X · First move is yours</small></div><div className="stats-card"><div className="eyebrow">YOUR MATCH RECORD</div><div className="stats"><div><strong>{data.stats.wins}</strong><span>WINS</span></div><div><strong>{data.stats.losses}</strong><span>LOSSES</span></div><div><strong>{data.stats.draws}</strong><span>DRAWS</span></div></div><p>{data.stats.wins+data.stats.losses+data.stats.draws} matches played. Every one counts.</p></div><div className="rules-note"><span className="rules-icon">#</span><div><strong>Small board. Endless possibilities.</strong><p>Take turns. Get three in a row.<br/>A full board without a winner is a draw.</p></div></div></aside><section className="dashboard-content"><nav className="tabs" aria-label="Playroom views"><button className={tab==='lobby'?'selected':''} onClick={()=>setTab('lobby')}><Grid2X2 size={17}/>Lobby</button><button className={tab==='history'?'selected':''} onClick={()=>setTab('history')}><HistoryIcon size={17}/>Match history</button></nav>{tab==='history'?<History games={data.history} userId={user.id}/>:<><div className="section-heading"><div><h2>Open challenges<span className="count">{data.challenges.length}</span></h2><p>Pick an opponent. Your board is one click away.</p></div><button className="icon-button refresh-button" aria-label="Refresh challenges" onClick={()=>void room.refresh()}><RefreshCw size={17}/></button></div>{!data.challenges.length?<div className="empty lobby-empty"><div className="empty-marks">× <span>○</span></div><h3>The next rivalry could be yours.</h3><p>No open challenges just yet.<br/>Create one and invite a player to the lobby.</p><span className="empty-hint"><span className="tiny-dot"/> Challenges appear here automatically</span></div>:<div className="challenge-list">{data.challenges.map(g=><article className="challenge-row" key={g.id}><div className="avatar opponent-avatar">{g.player_x_name.slice(0,1).toUpperCase()}</div><div><h3>{g.player_x_name}</h3><p><span className="tiny-dot"/>Waiting for an opponent · {new Date(g.created_at).toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'})}</p></div><button className="secondary" disabled={busy} onClick={()=>void room.perform('join',g.id)}>Join <ArrowUpRight size={16}/></button></article>)}</div>}<div className="lobby-foot"><Radio size={14}/><span>Challenges and moves update in real time.</span><span className="play-o">You join as ○</span></div></>}</section></div></>}
  </> }</main><footer><span>QALIM tickTack <span className="footer-dash">/</span> A good game brings people together.</span><span>PLAY FAIR. HAVE FUN.</span></footer></div>;
}
